### ISSUE TITLE
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\app.wpy

### ISSUE THREAD

**Issue by jeaxnew** [Observer-L/NFU-Guide-Map#1]
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\app.wpy
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\about.wpy
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\index.wpy
[Error] Missing files: ../config in C:\Users\x\NFU-Guide-Map-master\src\pages\routes.wpy
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\web-view.wpy 

这是什么问题？

**Comment by q948185662** [comment]
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\app.wpy
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\about.wpy
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\index.wpy
[Error] Missing files: ../config in C:\Users\x\NFU-Guide-Map-master\src\pages\routes.wpy
[Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\web-view.wpy

请问这是什么问题？

**Comment by Observer-L** [comment]
已更新

> [Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\app.wpy
> [Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\about.wpy
> [Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\index.wpy
> [Error] Missing files: ../config in C:\Users\x\NFU-Guide-Map-master\src\pages\routes.wpy
> [Error] Missing files: config in C:\Users\x\NFU-Guide-Map-master\src\pages\web-view.wpy
> 
> 请问这是什么问题？

已更新
