### ISSUE TITLE
未授权

### ISSUE THREAD

**Issue by fandudu** [Observer-L/NFU-Guide-Map#4]
![image](https://user-images.githubusercontent.com/15722726/63737119-e6e74f80-c8b7-11e9-992e-b837c9ae9dbb.png)
不是小程序的开发者，用了测试appid,显示插件未授权使用，请问怎么解决

**Comment by Observer-L** [comment]
app.json中去除Plugins，腾讯地图插件，项目中用wx.openLocation替代。
