### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Observer-L** [Observer-L/NFU-Guide-Map#5]
1. 文创-明信片
2. 地点收藏夹
3. 地点打卡集卡
4. 对话机器人 
https://openai.weixin.qq.com/
5. I18N 
https://developers.weixin.qq.com/miniprogram/dev/extended/utils/miniprogram-i18n/quickstart.html
6. 深夜模式适配 
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/darkmode.html
7. cms 
https://developers.weixin.qq.com/community/develop/article/doc/0002a401aa0e5814306af240351c13
8. 首次使用指引
9. API Mock
https://developers.weixin.qq.com/miniprogram/dev/devtools/api-mock.html
10. 骨架屏
https://developers.weixin.qq.com/miniprogram/dev/devtools/skeleton.html
11. 自动化
https://developers.weixin.qq.com/miniprogram/dev/devtools/auto/
12. 地图瓦片/手绘地图 （未开放）
https://developers.weixin.qq.com/community/develop/doc/000860943aced83af976624bc5bc00
https://lbs.qq.com/dev/console/customLayer/create

**Comment by bdingtech** [comment]
大佬是即将推出这些新功能吗？

**Comment by Observer-L** [comment]
> 大佬是即将推出这些新功能吗？

挖坑先😀

**Comment by bdingtech** [comment]
坐等大佬更新
